reponame: code.arista.io/atlas/pybsn
description: |
  Atlas repo
users:
  maintainers:
    - andi@arista.com
x-bar:
  version: beta
epoch: 1
ObsoleteNames:
  - github.com/bigswitch/pybsn

Epoch: 1
x-github-bridge:
  reviews:
    - image: test
      events:
        - type: pull_request
        - type: push
          branch-re: ^main$

